"""Declarative V&V v2 contracts and deterministic evidence runner."""

from solveur.verification.v2.runner import (
    ExternalUnavailableError,
    DuplicateJsonKeyError,
    ExecutionOutput,
    ResourceLimitedError,
    VnvExecutionError,
    VnvEvidence,
    VnvRunner,
    canonical_json_bytes,
    canonical_sha256,
    load_evidence,
    load_evidence_from_dict,
    load_cases,
    load_prospective_cases,
    load_json_strict,
    replay_case,
    validate_case,
)
from solveur.verification.v2.execution_identity import (
    EVIDENCE_AVAILABILITY,
    IDENTITY_SCHEMA_VERSION,
    PROVENANCE_KINDS,
    ExecutionIdentity,
    ExecutionIdentityError,
    InputFileIdentity,
)
from solveur.verification.v2.projection import (
    PublicBenchmarkRecord,
    PublicProjectionError,
    render_public_benchmark,
)
from solveur.verification.v2.resume import (
    ResumeArtifact,
    ResumeAssessment,
    ResumeContractError,
    SafeResumeRecord,
    assess_safe_resume,
)
from solveur.verification.v2.schema import (
    CASE_SCHEMA_VERSION,
    LEGACY_CASE_SCHEMA_VERSION,
    ORACLE_TYPES,
    VERDICTS,
    ExpectedFailureContract,
    VnvCase,
    VnvOracle,
    VnvSchemaError,
)

__all__ = [
    "CASE_SCHEMA_VERSION",
    "LEGACY_CASE_SCHEMA_VERSION",
    "ORACLE_TYPES",
    "VERDICTS",
    "VnvCase",
    "VnvOracle",
    "VnvSchemaError",
    "ExpectedFailureContract",
    "ExternalUnavailableError",
    "DuplicateJsonKeyError",
    "ExecutionOutput",
    "ResourceLimitedError",
    "VnvExecutionError",
    "VnvEvidence",
    "VnvRunner",
    "canonical_json_bytes",
    "canonical_sha256",
    "load_evidence",
    "load_evidence_from_dict",
    "load_cases",
    "load_prospective_cases",
    "load_json_strict",
    "replay_case",
    "validate_case",
    "IDENTITY_SCHEMA_VERSION",
    "EVIDENCE_AVAILABILITY",
    "PROVENANCE_KINDS",
    "ExecutionIdentity",
    "ExecutionIdentityError",
    "InputFileIdentity",
    "ResumeArtifact",
    "ResumeAssessment",
    "ResumeContractError",
    "SafeResumeRecord",
    "assess_safe_resume",
    "PublicBenchmarkRecord",
    "PublicProjectionError",
    "render_public_benchmark",
]
