"""Public package for the finite element solver."""

from solveur.version import __version__

from solveur.api.public import (
    assess_result,
    benchmark_large_model,
    check_large_readiness,
    check_mesh,
    convert_model_to_large,
    generate_large_tet4_block,
    inspect_large_model,
    import_gmsh_model,
    list_benchmarks,
    list_methods,
    load_large_model,
    load_model,
    qualify_large_tet4_pipeline,
    qualification_readiness,
    recommended_large_block,
    run_benchmark,
    run_linear_solver_verification,
    run_qualification_case,
    run_mitc4_validation,
    save_evidence,
    save_large_readiness,
    save_large_verification,
    save_model,
    save_result,
    save_result_csv,
    save_result_vtu,
    solve_large_model,
    solve_model,
    verify_evidence,
    verify_large_qualification,
)
from solveur.core.errors import (
    ExitCode,
    InfrastructureError,
    InputValidationError,
    MeshValidationError,
    NumericalConvergenceError,
    QualificationGateError,
)
from solveur.core.constraints import ConstraintTerm, LinearConstraint
from solveur.core.model import FiniteElementModel
from solveur.core.qualification import RunVerdict
from solveur.core.rbe import Rbe2Definition, Rbe3Definition

__all__ = [
    "__version__",
    "assess_result",
    "ExitCode",
    "InfrastructureError",
    "InputValidationError",
    "MeshValidationError",
    "NumericalConvergenceError",
    "QualificationGateError",
    "RunVerdict",
    "ConstraintTerm",
    "FiniteElementModel",
    "LinearConstraint",
    "Rbe2Definition",
    "Rbe3Definition",
    "benchmark_large_model",
    "check_large_readiness",
    "check_mesh",
    "convert_model_to_large",
    "generate_large_tet4_block",
    "inspect_large_model",
    "import_gmsh_model",
    "list_benchmarks",
    "list_methods",
    "load_large_model",
    "load_model",
    "qualify_large_tet4_pipeline",
    "qualification_readiness",
    "recommended_large_block",
    "run_benchmark",
    "run_linear_solver_verification",
    "run_qualification_case",
    "run_mitc4_validation",
    "save_evidence",
    "save_large_readiness",
    "save_large_verification",
    "save_model",
    "save_result",
    "save_result_csv",
    "save_result_vtu",
    "solve_large_model",
    "solve_model",
    "verify_evidence",
    "verify_large_qualification",
]
