"""TET4/TET10 structural h-convergence in tension, bending and torsion."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

import numpy as np

from solveur.benchmarks.gmsh_factory import BenchmarkMeshFactory
from solveur.benchmarks.solid import observed_convergence_order
from solveur.benchmarks.solid_extended import apply_consistent_circular_torsion
from solveur.core.qualification import enforce_qualification_policy
from solveur.core.router import AnalysisRouter
from solveur.io.json_writer import JsonResultWriter
from solveur.io.manifest import write_json_file
from solveur.io.model_writer import JsonModelWriter
from solveur.io.vtu_writer import VtuResultWriter
from solveur.mesh.gmsh_importer import GmshModelImporter
from solveur.verification.vnv_manifest import write_vnv_manifest
from solveur.verification.vnv_visualization import exterior_tet4_faces


class Tet10StructuralConvergenceCampaign:
    """Compare first- and second-order tetrahedra against three closed forms."""

    study_id = "VNV-TET10-STRUCTURAL-CONVERGENCE-012"
    box_sizes = (1.10, 0.85, 0.65, 0.50)
    traction_sizes = (0.80, 0.60, 0.45, 0.34)
    torsion_sizes = (0.50, 0.38, 0.30, 0.24)

    def __init__(self, output_dir: str | Path):
        self.output_dir = Path(output_dir).resolve()
        self.factory = BenchmarkMeshFactory()

    def run(self) -> dict[str, object]:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        traction = self._traction()
        bending = self._bending()
        torsion = self._torsion()
        checks = self._checks(traction, bending, torsion)
        passed = all(check["status"] == "PASS" for check in checks)
        summary: dict[str, object] = {
            "study_id": self.study_id,
            "status": "PASS_TECHNICAL_VERIFICATION" if passed else "FAIL",
            "maturity": "experimental",
            "purpose": "TET4/TET10 structural h-convergence",
            "references": {
                "traction": "uniform uniaxial Hooke solution",
                "bending": "Timoshenko cantilever tip displacement",
                "torsion": "Saint-Venant circular shaft twist",
            },
            "traction": traction,
            "bending": bending,
            "torsion": torsion,
            "checks": checks,
            "scope_limit": (
                "Small-strain isotropic linear elasticity. Nominal mesh sizes are matched; "
                "TET4 and TET10 meshes are independently generated by deterministic Gmsh runs."
            ),
        }
        write_json_file(self.output_dir / "summary.json", summary)
        self._plot_convergence(summary)
        self._write_report(summary)
        write_vnv_manifest(self.output_dir, self.study_id)
        return summary

    def _traction(self) -> dict[str, object]:
        length, width, height = 2.0, 1.0, 0.5
        young, poisson, stress = 70.0e9, 0.3, 10.0e6
        reference = stress * length / young
        families = {
            family: self._run_levels(
                "traction",
                family,
                self.traction_sizes,
                lambda mesh, order: self.factory.box_tetra(
                    mesh,
                    length=length,
                    width=width,
                    height=height,
                    mesh_size=order[0],
                    order=order[1],
                ),
                lambda name: _traction_setup(name, young, poisson, stress),
                lambda model, result: {
                    "response": _mean_end_displacement(model, result, "UX"),
                    "response_error": _relative(_mean_end_displacement(model, result, "UX"), reference),
                    "stress_error": _uniform_stress_error(result, stress),
                },
            )
            for family in ("TET4", "TET10")
        }
        return {"reference_end_ux": reference, "families": families}

    def _bending(self) -> dict[str, object]:
        length, width, height = 8.0, 1.0, 1.0
        young, poisson, traction = 70.0e9, 0.3, -1000.0
        shear = young / (2.0 * (1.0 + poisson))
        inertia = width * height**3 / 12.0
        reference = traction * length**3 / (3.0 * young * inertia)
        reference += traction * length / ((5.0 / 6.0) * shear * width * height)
        families = {
            family: self._run_levels(
                "bending",
                family,
                self.box_sizes,
                lambda mesh, order: self.factory.box_tetra(
                    mesh,
                    length=length,
                    width=width,
                    height=height,
                    mesh_size=order[0],
                    order=order[1],
                ),
                lambda name: _bending_setup(name, young, poisson, traction),
                lambda model, result: {
                    "response": _mean_end_displacement(model, result, "UZ"),
                    "response_error": _relative(_mean_end_displacement(model, result, "UZ"), reference),
                },
                plot_finest=True,
            )
            for family in ("TET4", "TET10")
        }
        return {"reference_tip_uz": reference, "families": families}

    def _torsion(self) -> dict[str, object]:
        length, radius = 3.0, 0.5
        young, poisson, torque = 80.0e9, 0.3, 1000.0
        shear = young / (2.0 * (1.0 + poisson))
        polar_moment = 0.5 * np.pi * radius**4
        reference = torque * length / (shear * polar_moment)
        families: dict[str, object] = {}
        for family in ("TET4", "TET10"):
            load_diagnostics: dict[str, float] = {}

            def prepare(model: object) -> None:
                load_diagnostics.clear()
                load_diagnostics.update(apply_consistent_circular_torsion(model, torque))

            def metrics(model: object, result: object) -> dict[str, float]:
                twist = _end_twist(model, result)
                return {
                    "response": twist,
                    "response_error": _relative(twist, reference),
                    "stress_error": _torsion_stress_error(model, result, torque, polar_moment),
                    "applied_torque_error": _relative(load_diagnostics["resultant_torque_x"], torque),
                    "force_resultant_ratio": load_diagnostics["resultant_force_norm"] / torque,
                }

            families[family] = self._run_levels(
                "torsion",
                family,
                self.torsion_sizes,
                lambda mesh, order: self.factory.cylinder_tetra(
                    mesh,
                    length=length,
                    radius=radius,
                    mesh_size=order[0],
                    order=order[1],
                ),
                lambda name: _torsion_setup(name, young, poisson),
                metrics,
                prepare=prepare,
                plot_finest=True,
            )
        return {
            "reference_twist": reference,
            "shear_modulus": shear,
            "polar_moment": polar_moment,
            "families": families,
        }

    def _run_levels(
        self,
        problem: str,
        family: str,
        sizes: tuple[float, ...],
        mesh_builder: Callable[[Path, tuple[float, int]], Path],
        setup_builder: Callable[[str], dict[str, Any]],
        metric_builder: Callable[[object, object], dict[str, float]],
        *,
        prepare: Callable[[object], None] | None = None,
        plot_finest: bool = False,
    ) -> dict[str, object]:
        rows = []
        for level, mesh_size in enumerate(sizes, start=1):
            prefix = f"{problem}_{family.lower()}_h{level}"
            mesh = mesh_builder(self.output_dir / f"{prefix}.msh", (mesh_size, 1 if family == "TET4" else 2))
            model, result = self._solve(mesh, setup_builder(family), prefix, prepare)
            row: dict[str, object] = {
                "level": level,
                "mesh_size": mesh_size,
                "node_count": model.node_count,
                "element_count": len(model.elements),
                "free_relative_residual": _free_residual(result),
                **metric_builder(model, result),
            }
            rows.append(row)
            if plot_finest and level == len(sizes) and family == "TET10":
                plot_tetra_vector(
                    self.output_dir / f"{problem}_tet10_deformation.png",
                    model,
                    np.asarray(result.displacements, dtype=float),
                    f"TET10 {problem} - maillage fin",
                )
        errors = np.asarray([row["response_error"] for row in rows], dtype=float)
        order = observed_convergence_order(np.asarray(sizes), np.maximum(errors, 1.0e-16))
        return {
            "levels": rows,
            "observed_order": order,
            "finest_response_error": float(errors[-1]),
            "error_reduction_ratio": float(errors[0] / max(errors[-1], np.finfo(float).tiny)),
            "maximum_free_relative_residual": max(float(row["free_relative_residual"]) for row in rows),
        }

    def _solve(
        self,
        mesh: Path,
        setup: dict[str, Any],
        prefix: str,
        prepare: Callable[[object], None] | None,
    ) -> tuple[object, object]:
        setup_path = self.output_dir / f"{prefix}.setup.json"
        write_json_file(setup_path, setup)
        imported = GmshModelImporter().import_model(mesh, setup_path)
        if prepare is not None:
            prepare(imported.model)
        model_path = self.output_dir / f"{prefix}.model.json"
        result_path = self.output_dir / f"{prefix}.result.json"
        JsonModelWriter().write(imported.model, model_path)
        result = enforce_qualification_policy(AnalysisRouter().solve(imported.model), imported.model)
        JsonResultWriter().write(result, result_path)
        VtuResultWriter().write(result, imported.model, self.output_dir / f"{prefix}.vtu")
        return imported.model, result

    @staticmethod
    def _checks(
        traction: dict[str, object],
        bending: dict[str, object],
        torsion: dict[str, object],
    ) -> list[dict[str, object]]:
        traction4 = traction["families"]["TET4"]
        traction10 = traction["families"]["TET10"]
        bending4 = bending["families"]["TET4"]
        bending10 = bending["families"]["TET10"]
        torsion4 = torsion["families"]["TET4"]
        torsion10 = torsion["families"]["TET10"]
        return [
            _upper("traction_tet4_patch", _maximum_field_error(traction4), 1.0e-8),
            _upper("traction_tet10_patch", _maximum_field_error(traction10), 1.0e-8),
            _upper("bending_tet10_finest", float(bending10["finest_response_error"]), 0.02),
            _upper("bending_tet10_monotonicity", _monotonicity_violation(bending10), 1.0e-12),
            _upper("bending_tet10_final_increment", _final_response_increment(bending10), 0.005),
            _lower(
                "bending_tet10_advantage",
                float(bending4["finest_response_error"]) / float(bending10["finest_response_error"]),
                10.0,
            ),
            _upper("torsion_tet10_finest", float(torsion10["finest_response_error"]), 0.01),
            _upper("torsion_tet10_stress", _finest_stress_error(torsion10), 0.02),
            _lower("torsion_tet10_reduction", float(torsion10["error_reduction_ratio"]), 2.0),
            _lower(
                "torsion_tet10_advantage",
                float(torsion4["finest_response_error"]) / float(torsion10["finest_response_error"]),
                1.5,
            ),
            _upper("torsion_load_balance", _maximum_torsion_load_error(torsion), 1.0e-10),
            _upper("all_free_residuals", _maximum_residual(traction, bending, torsion), 1.0e-8),
        ]

    def _plot_convergence(self, summary: dict[str, object]) -> None:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        figure, axes = plt.subplots(1, 3, figsize=(13.2, 4.2))
        for axis, key, title in zip(axes, ("traction", "bending", "torsion"), ("Traction", "Flexion", "Torsion")):
            for family, marker in (("TET4", "s"), ("TET10", "o")):
                rows = summary[key]["families"][family]["levels"]
                axis.loglog(
                    [row["mesh_size"] for row in rows],
                    [max(float(row["response_error"]), 1.0e-16) for row in rows],
                    marker=marker,
                    label=family,
                )
            axis.invert_xaxis()
            axis.set(title=title, xlabel="Taille nominale h", ylabel="Erreur relative")
            axis.grid(True, which="both", alpha=0.25)
            axis.legend()
        figure.tight_layout()
        figure.savefig(self.output_dir / "tet10_structural_convergence.png", dpi=180)
        plt.close(figure)

    def _write_report(self, summary: dict[str, object]) -> None:
        lines = [
            f"# {self.study_id}",
            "",
            f"Statut automatise : **{summary['status']}**",
            "",
            "Comparaison TET4/TET10 sur quatre tailles nominales par probleme.",
            "",
        ]
        for key, response in (("traction", "u_x"), ("bending", "u_z"), ("torsion", "theta")):
            lines.extend([f"## {key.capitalize()}", "", f"Grandeur comparee : `{response}`.", ""])
            lines.extend(_markdown_table(summary[key]))
        lines.extend(
            [
                "## Conclusion",
                "",
                "La traction constitue un patch affine. La flexion et la torsion mesurent la convergence structurelle.",
                "Le TET10 lineaire est accepte avec recommandations depuis la revue du 2026-07-18.",
                "",
                "![Convergence structurelle](tet10_structural_convergence.png)",
                "",
                "![Deformee de flexion](bending_tet10_deformation.png)",
                "",
                "![Deformee de torsion](torsion_tet10_deformation.png)",
                "",
            ]
        )
        (self.output_dir / "report.md").write_text("\n".join(lines), encoding="utf-8")


def _solid_setup(family: str, young: float, poisson: float) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "mesh_scale_to_m": 1.0,
        "units": {"system": "SI"},
        "verification_profile": "engineering",
        "analysis": {"type": "linear_static", "method": "direct"},
        "materials": {"solid": {"type": "isotropic_3d", "E": young, "nu": poisson, "density": 2700.0}},
        "groups": [
            {
                "name": "domain",
                "dimension": 3,
                "actions": [{"type": "elements", "element_type": family, "material": "solid"}],
            }
        ],
    }


def _traction_setup(family: str, young: float, poisson: float, stress: float) -> dict[str, Any]:
    setup = _solid_setup(family, young, poisson)
    setup["groups"].extend(
        [
            _fixed("x_min", 2, ["UX"]),
            _fixed("y_min", 2, ["UY"]),
            _fixed("z_min", 2, ["UZ"]),
            _traction("x_max", [stress, 0.0, 0.0]),
        ]
    )
    return setup


def _bending_setup(family: str, young: float, poisson: float, traction: float) -> dict[str, Any]:
    setup = _solid_setup(family, young, poisson)
    setup["groups"].extend([_fixed("x_min", 2, ["UX", "UY", "UZ"]), _traction("x_max", [0.0, 0.0, traction])])
    return setup


def _torsion_setup(family: str, young: float, poisson: float) -> dict[str, Any]:
    setup = _solid_setup(family, young, poisson)
    setup["groups"].append(_fixed("x_min", 2, ["UX", "UY", "UZ"]))
    return setup


def _fixed(name: str, dimension: int, dofs: list[str]) -> dict[str, Any]:
    return {"name": name, "dimension": dimension, "actions": [{"type": "fixed_dofs", "dofs": dofs}]}


def _traction(name: str, value: list[float]) -> dict[str, Any]:
    return {"name": name, "dimension": 2, "actions": [{"type": "surface_traction", "value": value}]}


def _mean_end_displacement(model: object, result: object, dof: str) -> float:
    nodes = np.asarray(model.nodes, dtype=float)
    selected = np.where(np.isclose(nodes[:, 0], np.max(nodes[:, 0])))[0]
    return float(np.mean([result.displacements[result.dofs.index(int(node), dof)] for node in selected]))


def _end_twist(model: object, result: object) -> float:
    nodes = np.asarray(model.nodes, dtype=float)
    selected = np.where(np.isclose(nodes[:, 0], np.max(nodes[:, 0])))[0]
    y = nodes[selected, 1]
    z = nodes[selected, 2]
    uy = np.asarray([result.displacements[result.dofs.index(int(node), "UY")] for node in selected])
    uz = np.asarray([result.displacements[result.dofs.index(int(node), "UZ")] for node in selected])
    return float(np.sum(y * uz - z * uy) / np.sum(y * y + z * z))


def _uniform_stress_error(result: object, stress: float) -> float:
    observed = np.asarray([row["stress"] for row in result.to_dict()["element_results"]], dtype=float)
    expected = np.zeros_like(observed)
    expected[:, 0] = stress
    return float(np.linalg.norm(observed - expected) / np.linalg.norm(expected))


def _torsion_stress_error(model: object, result: object, torque: float, polar_moment: float) -> float:
    observed = np.asarray([row["stress"] for row in result.to_dict()["element_results"]], dtype=float)
    centroids = np.asarray(
        [np.mean(model.nodes[np.asarray(element.nodes[:4], dtype=int)], axis=0) for element in model.elements]
    )
    expected = np.zeros_like(observed)
    expected[:, 3] = -torque * centroids[:, 2] / polar_moment
    expected[:, 5] = torque * centroids[:, 1] / polar_moment
    return float(np.linalg.norm(observed - expected) / max(np.linalg.norm(expected), np.finfo(float).tiny))


def _free_residual(result: object) -> float:
    return float(result.to_dict().get("audit", {}).get("equilibrium", {}).get("free_relative_residual", 0.0))


def _relative(value: float, reference: float) -> float:
    return abs(value - reference) / max(abs(reference), np.finfo(float).tiny)


def _maximum_field_error(family: dict[str, object]) -> float:
    return max(
        max(float(row["response_error"]), float(row["stress_error"]))
        for row in family["levels"]
    )


def _maximum_torsion_load_error(torsion: dict[str, object]) -> float:
    return max(
        max(float(row["applied_torque_error"]), float(row["force_resultant_ratio"]))
        for family in torsion["families"].values()
        for row in family["levels"]
    )


def _monotonicity_violation(family: dict[str, object]) -> float:
    errors = np.asarray([row["response_error"] for row in family["levels"]], dtype=float)
    return float(max(np.max(np.diff(errors)), 0.0))


def _final_response_increment(family: dict[str, object]) -> float:
    rows = family["levels"]
    return _relative(float(rows[-1]["response"]), float(rows[-2]["response"]))


def _finest_stress_error(family: dict[str, object]) -> float:
    return float(family["levels"][-1]["stress_error"])


def _maximum_residual(*problems: dict[str, object]) -> float:
    return max(
        float(family["maximum_free_relative_residual"])
        for problem in problems
        for family in problem["families"].values()
    )


def _upper(identifier: str, value: float, limit: float) -> dict[str, object]:
    return {"id": identifier, "value": value, "limit": limit, "status": "PASS" if value <= limit else "FAIL"}


def _lower(identifier: str, value: float, limit: float) -> dict[str, object]:
    return {"id": identifier, "value": value, "limit": limit, "status": "PASS" if value >= limit else "FAIL"}


def _markdown_table(problem: dict[str, object]) -> list[str]:
    lines = [
        "| Famille | Niveau | h | Elements | Reponse | Erreur relative |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for family, data in problem["families"].items():
        for row in data["levels"]:
            lines.append(
                f"| {family} | {row['level']} | {row['mesh_size']:.3f} | {row['element_count']} | "
                f"{row['response']:.8e} | {row['response_error']:.3e} |"
            )
    lines.append("")
    return lines


def plot_tetra_vector(path: Path, model: object, vector: np.ndarray, title: str) -> None:
    """Plot a colour-mapped TET10 deformation with visible exterior faces."""
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d.art3d import Line3DCollection, Poly3DCollection

    nodes = np.asarray(model.nodes, dtype=float)
    translations = np.zeros_like(nodes)
    dofs = model.dof_manager()
    for node in range(model.node_count):
        for component, dof in enumerate(("UX", "UY", "UZ")):
            translations[node, component] = vector[dofs.index(node, dof)]
    magnitude = np.linalg.norm(translations, axis=1)
    span = max(float(np.ptp(nodes, axis=0).max()), 1.0)
    scale = 0.15 * span / max(float(np.max(magnitude)), np.finfo(float).tiny)
    deformed = nodes + scale * translations
    corners = np.asarray([element.nodes[:4] for element in model.elements], dtype=int)
    edges = sample_tetra_edges(corners, 1500)
    faces, _ = exterior_tet4_faces(corners)
    figure = plt.figure(figsize=(9.2, 5.6))
    axis = figure.add_subplot(111, projection="3d")
    original_segments = [[nodes[first], nodes[second]] for first, second in edges]
    axis.add_collection3d(
        Line3DCollection(
            original_segments,
            colors="#555555",
            linewidths=0.45,
            alpha=0.7,
            linestyles="dashed",
        )
    )
    maximum = max(float(np.max(magnitude)), np.finfo(float).tiny)
    cmap = plt.get_cmap("cividis")
    face_values = np.asarray([float(np.mean(magnitude[face])) for face in faces])
    collection = Poly3DCollection(
        [deformed[face] for face in faces],
        facecolors=cmap(face_values / maximum),
        edgecolors="#111111",
        linewidths=0.35,
        alpha=0.96,
    )
    axis.add_collection3d(collection)
    axis.scatter([], [], [], color="#555555", marker="_", label="maillage initial")
    axis.scatter([], [], [], color=cmap(0.65), marker="s", label="deformee coloree")
    scalar = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=0.0, vmax=maximum))
    scalar.set_array([])
    colorbar = figure.colorbar(scalar, ax=axis, shrink=0.67, pad=0.08)
    colorbar.set_label("Norme du deplacement [m]")
    axis.set_title(f"{title} | amplification {scale:.3g}")
    all_points = np.vstack((nodes, deformed))
    center = np.mean(all_points, axis=0)
    radius = max(float(np.ptp(all_points, axis=0).max()) / 2.0, 1.0e-9)
    axis.set_xlim(center[0] - radius, center[0] + radius)
    axis.set_ylim(center[1] - radius, center[1] + radius)
    axis.set_zlim(center[2] - radius, center[2] + radius)
    axis.set_xlabel("X [m]")
    axis.set_ylabel("Y [m]")
    axis.set_zlabel("Z [m]")
    axis.view_init(elev=24.0, azim=-58.0)
    axis.legend()
    figure.tight_layout()
    figure.savefig(path, dpi=180)
    plt.close(figure)


def sample_tetra_edges(elements: np.ndarray, maximum: int) -> np.ndarray:
    """Return a deterministic sample of unique corner edges."""
    pairs = np.vstack(
        [elements[:, [i, j]] for i, j in ((0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3))]
    )
    edges = np.unique(np.sort(pairs, axis=1), axis=0)
    return edges[:: max(1, len(edges) // maximum)]
