"""Public API namespace."""

from solveur.api.public import (
    assess_result,
    analyze_large_scaling,
    analyze_petsc_tuning,
    benchmark_large_model,
    collect_large_runtime_environment,
    check_large_readiness,
    check_mesh,
    convert_model_to_large,
    generate_large_tet4_block,
    generate_large_tet4_cantilever,
    inspect_model,
    inspect_large_model,
    import_gmsh_model,
    import_cantilever_vnv_study,
    import_torsion_vnv_study,
    list_benchmarks,
    list_demonstrations,
    list_methods,
    load_large_model,
    load_distributed_large_model,
    load_model,
    parse_petsc_log_view,
    postprocess_large_model,
    qualify_large_tet4_pipeline,
    qualification_readiness,
    recommended_large_block,
    run_large_scale_campaign,
    run_large_preconditioner_campaign,
    run_qualification_campaign,
    run_qualification_case,
    run_release_vv,
    run_benchmark,
    run_demonstration,
    run_contact_verification,
    run_linear_solver_verification,
    run_mitc4_validation,
    run_torsion_stress_probe,
    run_vnv_study,
    save_audit_markdown,
    save_evidence,
    save_large_readiness,
    save_large_runtime_environment,
    save_large_verification,
    save_model,
    save_result,
    save_result_csv,
    save_result_vtu,
    solve_large_model,
    solve_model,
    verify_evidence,
    verify_large_qualification,
    write_petsc_profile_report,
)
from solveur.core.errors import (
    ExitCode,
    InfrastructureError,
    InputValidationError,
    MeshValidationError,
    NumericalConvergenceError,
    QualificationGateError,
)
from solveur.core.constraints import ConstraintTerm, LinearConstraint
from solveur.core.model import FiniteElementModel
from solveur.core.qualification import RunVerdict
from solveur.core.rbe import Rbe2Definition, Rbe3Definition
from solveur.materials.composite import OrthotropicLamina
from solveur.mesh.quality import MeshQualityThresholds
from solveur.mesh.validation import MeshValidator
from solveur.verification.tet4_structured_convergence import (
    StructuredTet4ConvergencePlan,
    run_structured_tet4_study,
)

__all__ = [
    "assess_result",
    "analyze_large_scaling",
    "analyze_petsc_tuning",
    "ExitCode",
    "InfrastructureError",
    "InputValidationError",
    "MeshValidationError",
    "NumericalConvergenceError",
    "QualificationGateError",
    "RunVerdict",
    "ConstraintTerm",
    "FiniteElementModel",
    "LinearConstraint",
    "Rbe2Definition",
    "Rbe3Definition",
    "MeshQualityThresholds",
    "MeshValidator",
    "OrthotropicLamina",
    "StructuredTet4ConvergencePlan",
    "benchmark_large_model",
    "collect_large_runtime_environment",
    "check_large_readiness",
    "check_mesh",
    "convert_model_to_large",
    "generate_large_tet4_block",
    "generate_large_tet4_cantilever",
    "inspect_model",
    "inspect_large_model",
    "import_gmsh_model",
    "import_cantilever_vnv_study",
    "import_torsion_vnv_study",
    "list_benchmarks",
    "list_demonstrations",
    "list_methods",
    "load_large_model",
    "load_distributed_large_model",
    "load_model",
    "parse_petsc_log_view",
    "postprocess_large_model",
    "qualify_large_tet4_pipeline",
    "qualification_readiness",
    "recommended_large_block",
    "run_large_scale_campaign",
    "run_large_preconditioner_campaign",
    "run_qualification_campaign",
    "run_qualification_case",
    "run_release_vv",
    "run_benchmark",
    "run_demonstration",
    "run_contact_verification",
    "run_linear_solver_verification",
    "run_mitc4_validation",
    "run_torsion_stress_probe",
    "run_structured_tet4_study",
    "run_vnv_study",
    "save_audit_markdown",
    "save_evidence",
    "save_large_readiness",
    "save_large_runtime_environment",
    "save_large_verification",
    "save_model",
    "save_result",
    "save_result_csv",
    "save_result_vtu",
    "solve_large_model",
    "solve_model",
    "verify_evidence",
    "verify_large_qualification",
    "write_petsc_profile_report",
]
